<script lang="ts">
	import Icon from '$lib/components/icon.svelte';
	let { data, form } = $props();
	let createOpen = $state(false);
	const badge: Record<string,string> = { draft:'badge-ghost', diajukan:'badge-warning', diperiksa:'badge-info', disetujui:'badge-success', ditolak:'badge-error', diterbitkan:'badge-primary' };
	const label = (value:string) => value.replaceAll('_',' ').replace(/\b\w/g,(char)=>char.toUpperCase());
	const date = (value:string|null) => value ? new Intl.DateTimeFormat('id-ID',{dateStyle:'medium',timeStyle:'short'}).format(new Date(value)) : '-';
</script>

<div class="space-y-4">
	<header class="flex flex-col gap-3 lg:flex-row lg:items-end lg:justify-between"><div><h2 class="text-2xl font-bold">Pusat Persetujuan</h2><p class="text-base-content/65 text-sm">Dokumen disetujui per versi dan tidak menimpa snapshot yang telah diterbitkan.</p></div>{#if data.capabilities.submit}<button class="btn btn-primary btn-soft shadow-none" type="button" onclick={() => createOpen=true}><Icon name="plus" /> Ajukan Dokumen</button>{/if}</header>
	{#if form?.fail}<div class="alert alert-error py-2">{form.fail}</div>{/if}{#if form?.message}<div class="alert alert-success py-2">{form.message}</div>{/if}
	<form method="GET" class="grid gap-2 rounded-lg border border-base-300 bg-base-100 p-3 shadow-sm md:grid-cols-[1fr_190px_auto]"><input class="input input-bordered" name="q" value={data.filters.q} placeholder="Cari judul atau jenis dokumen..."/><select class="select select-bordered" name="status"><option value="">Semua status</option>{#each ['draft','diajukan','diperiksa','disetujui','ditolak','diterbitkan'] as status}<option value={status} selected={data.filters.status===status}>{label(status)}</option>{/each}</select><button class="btn btn-soft" type="submit"><Icon name="search" /> Cari</button></form>
	<div class="overflow-x-auto rounded-lg border border-base-300 bg-base-100 shadow-sm"><table class="table table-zebra"><thead><tr><th>Dokumen</th><th>Versi</th><th>Status</th><th>Catatan</th><th>Pembaruan</th><th class="text-right">Aksi</th></tr></thead><tbody>{#each data.rows as item}<tr><td><strong>{item.titleSnapshot}</strong><div class="text-xs opacity-60">{label(item.documentType)}{item.entityId ? ` · #${item.entityId}` : ''}</div></td><td>v{item.version}</td><td><span class={`badge ${badge[item.status]??'badge-ghost'}`}>{label(item.status)}</span></td><td class="max-w-xs text-sm">{item.note || '-'}</td><td class="whitespace-nowrap text-sm">{date(item.updatedAt || item.createdAt)}</td><td><div class="flex flex-wrap justify-end gap-1">
		{#if (item.status==='draft'||item.status==='ditolak')&&data.capabilities.submit}<form method="POST" action="?/transition"><input type="hidden" name="id" value={item.id}/><button class="btn btn-primary btn-soft btn-sm" name="target" value="diajukan">Ajukan</button></form>{/if}
		{#if item.status==='diajukan'&&data.capabilities.review}<form method="POST" action="?/transition"><input type="hidden" name="id" value={item.id}/><button class="btn btn-info btn-soft btn-sm" name="target" value="diperiksa">Periksa</button></form>{/if}
		{#if (item.status==='diajukan'||item.status==='diperiksa')&&data.capabilities.approve}<form method="POST" action="?/transition" class="flex gap-1"><input type="hidden" name="id" value={item.id}/><input class="input input-bordered input-sm w-32" name="note" placeholder="Catatan"/><button class="btn btn-success btn-soft btn-sm" name="target" value="disetujui">Setujui</button><button class="btn btn-error btn-soft btn-sm" name="target" value="ditolak">Tolak</button></form>{/if}
		{#if item.status==='disetujui'&&data.capabilities.publish}<form method="POST" action="?/transition"><input type="hidden" name="id" value={item.id}/><button class="btn btn-primary btn-sm" name="target" value="diterbitkan">Terbitkan</button></form>{/if}
		{#if ['disetujui','diterbitkan','ditolak'].includes(item.status)&&data.capabilities.submit}<form method="POST" action="?/revise"><input type="hidden" name="id" value={item.id}/><button class="btn btn-soft btn-sm" type="submit"><Icon name="repeat" /> Revisi</button></form>{/if}
	</div></td></tr>{:else}<tr><td colspan="6" class="py-12 text-center opacity-60">Belum ada dokumen dalam alur persetujuan.</td></tr>{/each}</tbody></table></div>
	{#if data.page.totalPages>1}<div class="join flex justify-center">{#each Array.from({length:data.page.totalPages},(_,i)=>i+1) as page}<a class:btn-active={page===data.page.currentPage} class="btn join-item btn-sm" href={`?q=${encodeURIComponent(data.filters.q)}&status=${data.filters.status}&page=${page}`}>{page}</a>{/each}</div>{/if}
</div>

{#if createOpen}<div class="modal modal-open"><div class="modal-box"><h3 class="text-xl font-bold">Buat Draft Persetujuan</h3><form method="POST" action="?/create" class="mt-4 space-y-4"><label class="form-control"><span class="label-text mb-1">Jenis Dokumen</span><select class="select select-bordered" name="documentType" required>{#each data.documentTypes as type}<option value={type}>{label(type)}</option>{/each}</select></label><label class="form-control"><span class="label-text mb-1">Judul Dokumen</span><input class="input input-bordered" name="title" required/></label><label class="form-control"><span class="label-text mb-1">ID sumber (opsional)</span><input class="input input-bordered" name="entityId"/></label><label class="form-control"><span class="label-text mb-1">Catatan</span><textarea class="textarea textarea-bordered" name="note" rows="3"></textarea></label><div class="modal-action"><button class="btn" type="button" onclick={() => createOpen=false}>Batal</button><button class="btn btn-primary" type="submit"><Icon name="save" /> Simpan Draft</button></div></form></div><button class="modal-backdrop" type="button" onclick={() => createOpen=false}>Tutup</button></div>{/if}
