import { ensureSchema } from './ensure-helper';

export async function ensureAbsensiDigitalSchema() {
	await ensureSchema('absensi-digital', [
		`CREATE TABLE IF NOT EXISTS "absensi_harian" (
			"id" integer PRIMARY KEY AUTOINCREMENT NOT NULL,
			"sekolah_id" integer NOT NULL REFERENCES "sekolah"("id") ON DELETE CASCADE,
			"semester_id" integer NOT NULL REFERENCES "semester"("id") ON DELETE CASCADE,
			"kelas_id" integer NOT NULL REFERENCES "kelas"("id") ON DELETE CASCADE,
			"murid_id" integer NOT NULL REFERENCES "murid"("id") ON DELETE CASCADE,
			"tanggal" text NOT NULL,
			"status" text NOT NULL,
			"waktu_scan" text,
			"metode" text NOT NULL,
			"petugas_user_id" integer REFERENCES "auth_user"("id") ON DELETE SET NULL,
			"catatan" text,
			"created_at" text NOT NULL,
			"updated_at" text
		)`,
		`CREATE UNIQUE INDEX IF NOT EXISTS "absensi_harian_murid_tanggal_unique" ON "absensi_harian" ("murid_id", "tanggal")`,
		`CREATE INDEX IF NOT EXISTS "absensi_harian_sekolah_tanggal_idx" ON "absensi_harian" ("sekolah_id", "tanggal")`,
		`CREATE INDEX IF NOT EXISTS "absensi_harian_kelas_tanggal_idx" ON "absensi_harian" ("kelas_id", "tanggal")`,
		`CREATE INDEX IF NOT EXISTS "absensi_harian_semester_idx" ON "absensi_harian" ("semester_id")`,
		`CREATE INDEX IF NOT EXISTS "absensi_harian_status_idx" ON "absensi_harian" ("status")`,
		`CREATE TABLE IF NOT EXISTS "kegiatan_absensi" (
			"id" integer PRIMARY KEY AUTOINCREMENT NOT NULL,
			"sekolah_id" integer NOT NULL REFERENCES "sekolah"("id") ON DELETE CASCADE,
			"kode" text NOT NULL,
			"nama" text NOT NULL,
			"kategori" text NOT NULL,
			"urutan" integer DEFAULT 0 NOT NULL,
			"jam_mulai" text,
			"batas_terlambat" text,
			"jam_selesai" text,
			"auto_alfa" integer DEFAULT 1 NOT NULL,
			"masuk_rapor" integer DEFAULT 0 NOT NULL,
			"aktif" integer DEFAULT 1 NOT NULL,
			"akses_edit" text DEFAULT 'semua' NOT NULL,
			"created_at" text NOT NULL,
			"updated_at" text
		)`,
		`CREATE UNIQUE INDEX IF NOT EXISTS "kegiatan_absensi_sekolah_kode_unique" ON "kegiatan_absensi" ("sekolah_id", "kode")`,
		`CREATE INDEX IF NOT EXISTS "kegiatan_absensi_sekolah_idx" ON "kegiatan_absensi" ("sekolah_id")`,
		`CREATE INDEX IF NOT EXISTS "kegiatan_absensi_kategori_idx" ON "kegiatan_absensi" ("kategori")`,
		`CREATE INDEX IF NOT EXISTS "kegiatan_absensi_aktif_idx" ON "kegiatan_absensi" ("aktif")`,
		`CREATE TABLE IF NOT EXISTS "absensi_kegiatan" (
			"id" integer PRIMARY KEY AUTOINCREMENT NOT NULL,
			"sekolah_id" integer NOT NULL REFERENCES "sekolah"("id") ON DELETE CASCADE,
			"semester_id" integer NOT NULL REFERENCES "semester"("id") ON DELETE CASCADE,
			"kelas_id" integer NOT NULL REFERENCES "kelas"("id") ON DELETE CASCADE,
			"murid_id" integer NOT NULL REFERENCES "murid"("id") ON DELETE CASCADE,
			"kegiatan_id" integer NOT NULL REFERENCES "kegiatan_absensi"("id") ON DELETE CASCADE,
			"tanggal" text NOT NULL,
			"status" text NOT NULL,
			"waktu_scan" text,
			"metode" text NOT NULL,
			"petugas_user_id" integer REFERENCES "auth_user"("id") ON DELETE SET NULL,
			"catatan" text,
			"auto_alfa" integer DEFAULT 0 NOT NULL,
			"created_at" text NOT NULL,
			"updated_at" text
		)`,
		`CREATE UNIQUE INDEX IF NOT EXISTS "absensi_kegiatan_murid_kegiatan_tanggal_unique" ON "absensi_kegiatan" ("murid_id", "kegiatan_id", "tanggal")`,
		`CREATE INDEX IF NOT EXISTS "absensi_kegiatan_sekolah_tanggal_idx" ON "absensi_kegiatan" ("sekolah_id", "tanggal")`,
		`CREATE INDEX IF NOT EXISTS "absensi_kegiatan_kelas_tanggal_idx" ON "absensi_kegiatan" ("kelas_id", "tanggal")`,
		`CREATE INDEX IF NOT EXISTS "absensi_kegiatan_semester_idx" ON "absensi_kegiatan" ("semester_id")`,
		`CREATE INDEX IF NOT EXISTS "absensi_kegiatan_kegiatan_tanggal_idx" ON "absensi_kegiatan" ("kegiatan_id", "tanggal")`,
		`CREATE INDEX IF NOT EXISTS "absensi_kegiatan_status_idx" ON "absensi_kegiatan" ("status")`,
		`CREATE INDEX IF NOT EXISTS "absensi_kegiatan_metode_idx" ON "absensi_kegiatan" ("metode")`,
		`CREATE TABLE IF NOT EXISTS "qr_murid" (
			"id" integer PRIMARY KEY AUTOINCREMENT NOT NULL,
			"murid_id" integer NOT NULL REFERENCES "murid"("id") ON DELETE CASCADE,
			"token_hash" text NOT NULL,
			"token_version" integer DEFAULT 1 NOT NULL,
			"issued_at" text NOT NULL,
			"revoked_at" text,
			"created_at" text NOT NULL,
			"updated_at" text
		)`,
		`CREATE UNIQUE INDEX IF NOT EXISTS "qr_murid_token_hash_unique" ON "qr_murid" ("token_hash")`,
		`CREATE INDEX IF NOT EXISTS "qr_murid_murid_idx" ON "qr_murid" ("murid_id")`,
		`CREATE INDEX IF NOT EXISTS "qr_murid_revoked_idx" ON "qr_murid" ("revoked_at")`
	]);
}